const config = require("../config");
const { getRandomEmoji, getStatusEmoji } = require("./functions");
const { getText } = require('./smartReply');
const { aiReply } = require('./aiReply');
const outgoingGuard = require('./outgoingGuard');

function isStatus(msg) {
  return msg?.key?.remoteJid === "status@broadcast";
}

const sentMessageIds = new Set();
const pendingOutgoing = new Set();
const processedMessageIds = new Set();
const recentAutoReplies = new Map();

function rememberSent(id) {
  if (!id) return;
  sentMessageIds.add(id);
  setTimeout(() => sentMessageIds.delete(id), 120000);
}

function rememberOutgoing(jid, text) {
  if (!jid || !text) return;
  const key = `${jid}|${String(text).trim()}`;
  pendingOutgoing.add(key);
  setTimeout(() => pendingOutgoing.delete(key), 120000);
}

async function autoFeatures(sock) {
  if (config.alwaysOnline) {
    try { await sock.sendPresenceUpdate("available"); } catch (_) {}
    setInterval(async () => {
      try { await sock.sendPresenceUpdate("available"); } catch (_) {}
    }, 25000);
  }

  if (config.autoCallReject) {
    sock.ev.on("call", async (calls) => {
      for (const call of calls || []) {
        try {
          if (call?.id && call?.from) {
            await sock.rejectCall(call.id, call.from);
            console.log(`Rejected incoming call from ${call.from}`);
          }
        } catch (e) {
          console.log("Call reject error:", e?.message || e);
        }
      }
    });
  }

  sock.ev.on("messages.upsert", async ({ messages }) => {
    for (const msg of messages || []) {
      if (!msg?.message) continue;
      // Never auto-reply to messages actually sent by the bot itself. This is
      // especially important in WhatsApp self-chat, where both owner-typed
      // and bot-generated messages can have fromMe=true.
      if (outgoingGuard.isBotMessage(msg)) continue;
      const messageId = msg.key?.id;
      if (messageId) {
        if (processedMessageIds.has(messageId)) continue;
        processedMessageIds.add(messageId);
        setTimeout(() => processedMessageIds.delete(messageId), 120000);
      }
      // Ignore messages generated by this bot. In self-chat WhatsApp marks both
      // the owner's and bot's messages as fromMe, so we use the outgoing text
      // signature instead of blindly ignoring every fromMe message.
      if (messageId && sentMessageIds.has(messageId)) continue;

      if (isStatus(msg)) {
        if (config.autoStatusSeen) {
          try { await sock.readMessages([msg.key]); } catch (_) {}
        }
        if (config.autoStatusLike) {
          try {
            await sock.sendMessage("status@broadcast", {
              react: { text: getStatusEmoji(), key: msg.key }
            }, { statusJidList: [msg.key.participant || msg.key.remoteJid] });
          } catch (e) {
            console.log("Status reaction error:", e?.message || e);
          }
        }
        continue;
      }

      const jid = msg.key.remoteJid;
      if (!jid) continue;

      if (config.autoTyping) {
        try { await sock.sendPresenceUpdate("composing", jid); } catch (_) {}
      }

      if (config.autoRecording) {
        try {
          await new Promise(resolve => setTimeout(resolve, 700));
          await sock.sendPresenceUpdate("recording", jid);
        } catch (_) {}
      }

      if (config.autoReact) {
        try {
          await sock.sendMessage(jid, {
            react: { text: getRandomEmoji(), key: msg.key }
          });
        } catch (_) {}
      }

      if (config.autoReply) {
        try {
          const originalText = getText(msg);
          if (!originalText || originalText.startsWith(config.prefix || '.')) continue;

          // Do not auto-reply to tiny/accidental fragments such as T, Ka, Vs,
          // single emojis, or repeated short taps. This prevents noisy replies
          // in self-chat and normal chats.
          const compact = originalText.replace(/[\s\p{P}\p{S}]+/gu, '');
          if (compact.length < 3) continue;

          // Same incoming text in the same chat gets at most one auto-reply
          // within the cooldown window. This stops repeated/spam replies.
          const incomingKey = `${jid}|${originalText.toLowerCase().trim()}`;
          const lastReplyAt = recentAutoReplies.get(incomingKey) || 0;
          if (Date.now() - lastReplyAt < 30000) continue;
          recentAutoReplies.set(incomingKey, Date.now());
          setTimeout(() => {
            if (recentAutoReplies.get(incomingKey) && Date.now() - recentAutoReplies.get(incomingKey) >= 30000) {
              recentAutoReplies.delete(incomingKey);
            }
          }, 31000);

          // Keyword replies are checked first when configured. Otherwise use the
          // built-in smart reply engine so every normal text message gets a response.
          const map = config.autoReplyKeywords || {};
          const lower = originalText.toLowerCase();
          const match = Object.keys(map).find(k => k && lower.includes(k.toLowerCase()));
          const reply = match ? map[match] : (config.smartAutoReply ? await aiReply(originalText, jid) : null);
          if (reply) {
            await new Promise(resolve => setTimeout(resolve, 500 + Math.min(originalText.length * 12, 1800)));
            rememberOutgoing(jid, reply);
            const sent = await sock.sendMessage(jid, { text: reply }, { quoted: msg });
            rememberSent(sent?.key?.id);
          }
        } catch (_) {}
      }
    }
  });
}

module.exports = autoFeatures;
